### ISSUE TITLE
Template engine includes regression from metalsmith-templates

### ISSUE THREAD

**Issue by madeofpeople** [superwolff/metalsmith-in-place#15] opened 2015-07-20 12:48 UTC
I understand, and support the splitting of metalsmith-in-place and layouts from metalsmith-templates, but one bit of functionality that was very useful to me, is not possible with in metalsmith-in-place that does in fact work in metalsmith-templates when the inPlace key is set to true, file includes.

swig example
```
/*!
Component Name

Component description

Markup:
{% include "components/molecules/cta/cta.html" %}
*/

.cta-wrapper {
  @extend .clearfix;
  clear: both;
  background: #dedede;
  .cta {
    text-align: center;
  }
}
```

results in:
```
> metalsmith -c kstatic_preprocess_scss.json
  Metalsmith · ENOENT, no such file or directory '/components/molecules/cta/cta.html'
```

stranger yet changing the path with ```../``` has no effect on the error so using ```{% include "components/molecules/cta/cta.html" %}``` results in no modification to the path in the error.

Which is to say both
```{% include "components/molecules/cta/cta.html" %}```
and
```{% include "../../../components/molecules/cta/cta.html" %}```
result in…
```Metalsmith · ENOENT, no such file or directory '/components/molecules/cta/cta.html'```

The same example works perfectly with metalsmith-templates when the inPlace option is on.

**Comment by ismay** [comment] 2015-07-20 16:52
Could be because of the changes that were made to metalsmith-templates after the fork, or because of the options that were removed (maybe directory). I'll merge in the upstream changes and check this out.

Let me know if you find what's causing this in the meantime.

**Comment by madeofpeople** [comment] 2015-07-20 18:50
Thanks, will report back if I uncover anything.

**Comment by ismay** [comment] 2015-07-26 14:46
It seems like [this](https://github.com/superwolff/metalsmith-in-place/blob/master/lib/index.js#L66) is the problem. We're rendering a string with `metalsmith-in-place`, instead of a file that `metalsmith-layouts` renders. Which is probably the reason that consolidate can't resolve any paths, because it doesn't have a starting point.

Weird thing is that metalsmith-in-place is exactly the same as the latest version of metalsmith-templates with `inplace: true;`, so results should be exactly the same. I'll have to experiment to see what would be the best way to address this.

**Comment by ismay** [comment] 2015-08-01 10:02
I've checked it out, and this isn't a regression as far as I can tell. `metalsmith-templates` with `inPlace: true` behaves exactly the same as `metalsmith-in-place`. The reason why you can't use partials or file includes with `metalsmith-in-place` is because the contents of each file are passed to consolidate as a string, instead of passing it a file path (which consolidate can then use to resolve paths).

Now, passing the template as a string (`data.contents` to be precise) is the best way to deal with in-place templating for metalsmith, since otherwise the frontmatter won't be filtered out. Downside is that stuff like partials won't work.

Of course, this not being a regression does not mean that including partials shouldn't work, but at least nothing has been broken. I'm looking at a way to allow for easy partial includes to solve the issue. So I'll be closing this since it doesn't seem to be a regression. Feel free to ask any further questions though.

---

p.s.: my guess would be that you were using both `inPlace: false` and `inPlace: true` in your build process, and that `inPlace: false` was how the includes were resolved. If not, then I'd be happy to see a reduced test case demonstrating how exactly it worked. For now, you could use `metalsmith-layouts` to replicate your previous setup, and resolve partials/includes.

**Comment by madeofpeople** [comment] 2015-08-01 14:44
Do you recommend I open another issue without regression in the title?
The lack of support for includes is still supported in metalsmith templates and missing here.
Do you think it's a reasonable enough use case to support?

I was not using both ```inPlace: true``` and ```inPlace: false```.

Using metalsmith-layouts will not work since were not really running them through templates, and adding a third file to the equation only complicates things.

Here's a simple use-case.
Using metalsmith-in-place, I get the aforementioned error:
```
> metalsmith -c kstatic_preprocess_scss.json
  Metalsmith · ENOENT, no such file or directory '/components/molecules/cta/cta.html'
```

Using metalsmith-templates: 
```
{
  "source": "components",
  "destination": "src/components/",
  "plugins": {
    "metalsmith-debug": {},
    "metalsmith-templates": {
      "engine":"swig",
      "inPlace": true,
      "directory": "/",
      "pattern": "**/*.scss"
    }
  }
}
```

Structure of the components tree:
```
RojoAir-2:tout thiago$ tree .
.
components/
└── molecules
    └── tout
        ├── _tout.scss
        └── tout.html

```

contents of _tout.scss:
```
/*
Tout Example

A tout to call attention to important things
deserving more than a little link.

Markup:
{% include "components/molecules/tout/tout.html" %}

Styleguide 5.1.1
*/
```

contents of tout.html:
```
<h1>Hello World</h1>
```

output:
```
/*
Tout Example

A tout to call attention to important things
deserving more than a little link.

Markup:
<h1>Hello World</h1>


Styleguide 5.2.6
*/
```

**Comment by ismay** [comment] 2015-08-05 10:29
> Do you recommend I open another issue without regression in the title?

No that won't be necessary. I'm working on support for partials and includes. I just closed this because I couldn't prove it was a regression.

> Do you think it's a reasonable enough use case to support?

Totally.

I've tested the example you gave me with the latest versions of metalsmith-templates and metalsmith-in-place and both gave me identical results. With metalsmith-in-place this `metalsmith.json`:

```json
{
  "source": "components",
  "destination": "src/components/",
  "plugins": {
    "metalsmith-debug": {},
    "metalsmith-in-place": {
      "engine":"swig",
      "pattern": "**/*.scss"
    }
  }
}
```

Gives me:

```
/*
Tout Example

A tout to call attention to important things
deserving more than a little link.

Markup:
<h1>Hello World</h1>

Styleguide 5.1.1
*/
```

Just like the result I got with metalsmith-templates (with the only difference being an added `inPlace: true` in the config). I've left out the `directory` option for both configs since it isn't used for in-place templating. So I'm not encountering the problems you mentioned. Can you find another way to reproduce them?

**Comment by madeofpeople** [comment] 2015-08-05 12:28
Thanks,
I'll run through the paces again sometime this week.

**Comment by ismay** [comment] 2015-08-07 14:57
I'm assuming this has been resolved. If not let me know and I'll reopen.

**Closed by ismay** 2015-08-07 14:57 UTC
Labels: bug
